//
//  REMOVERDEPOIS.swift
//  iVacina
//
//  Created by Alan Silva on 04/12/19.
//  Copyright © 2019 Alan Silva. All rights reserved.
//

import Foundation


class RemoverDepois {
    
    let tempUser: Person = Person(nome: "Alan Silva", email: "alan.bezerra10@gmail.com", imagem: "alan.jpg", grupo: .Adulto, tipoSanguineo: .A, hipertenso: false, diabetico: true, doadorOrgaos: true, pcd: false,
                                  vacinasCrianca: [[ .BCG : true,
                                                     .Hepatite_B : false,
                                                     .Penta_1_Dose : true,
                                                     .Poliomielite_1_Dose : false,
                                                     .Poliomielite_2_Dose : true,
                                                     .Poliomielite_3_Dose : false,
                                                     .Pneumococica_10 : true,
                                                     .Rotavirus_Humano_1_Dose : false,
                                                     .Meningococica_C : true,
                                                     .Penta_2_Dose : false,
                                                     .Pneumococica_10_Valente : true,
                                                     .Rotavirus_Humano_2_Dose : false,
                                                     .Febre_Amarela : true,
                                                     .Triplice_Viral : false,
                                                     .Pneumococica_Reforco : true,
                                                     .Meningococica_Reforco : false,
                                                     .Hepatite_A : true,
                                                     .Tetra_Viral : false,
                                                     .DTP : true,
                                                     .Varicela : false]],
                                  vacinasAdolescente: [[ .HPV_1_Dose : true,
                                                         .HPV_2_Dose : true,
                                                         .Meningococica_C : true,
                                                         .Hepatite_B : true,
                                                         .Febre_Amarela_1_Dose : true,
                                                         .Dupla_Adulto_DT : true,
                                                         .Triplice_Viral : true,
                                                         .Pneumococica_23_Valente : true]],
                                  vacinasAdulto: [[.Dupla_Adulto_DT : true,
                                                   .Gripe : true,
                                                   .Meningite_BACWY : true,
                                                   .Hpv : true,
                                                   .Pneumonia : true,
                                                   .Herpes_Zoster : true,
                                                   .Febre_Amarela : true,
                                                   .Hepatite_B : true,
                                                   .Triplice_Viral : true,
                                                   .Hepatite_A : true,
                                                   .Varicela : true]],
                                  vacinasIdoso: [[ .Hepatite_B : true,
                                                   .Febre_Amarela : true,
                                                   .Dupla_Adulto_DT : true,
                                                   .Pneumococica_23_Valente : true,
                                                   .Gripe_Anual : true]],
                                  vacinasGestante: [[.Hepatite_B : true,
                                                     .Dupla_Adulto_DT : true,
                                                     .dTpa : true,
                                                     .Influenza : true]],
                                  dependentes: [Dependente(nome: "Davi Silva", imagem: "davi.jpg", grupo: .Crianca, tipoSanguineo: .B_, hipertenso: false, diabetico: true, doadorOrgaos: true, pcd: false,
                                                           vacinasCrianca: [[ .BCG : true,
                                                                              .Hepatite_B : true,
                                                                              .Penta_1_Dose : true,
                                                                              .Poliomielite_1_Dose : true,
                                                                              .Poliomielite_2_Dose : true,
                                                                              .Poliomielite_3_Dose : true,
                                                                              .Pneumococica_10 : true,
                                                                              .Rotavirus_Humano_1_Dose : true,
                                                                              .Meningococica_C : true,
                                                                              .Penta_2_Dose : true,
                                                                              .Pneumococica_10_Valente : true,
                                                                              .Rotavirus_Humano_2_Dose : true,
                                                                              .Febre_Amarela : true,
                                                                              .Triplice_Viral : true,
                                                                              .Pneumococica_Reforco : true,
                                                                              .Meningococica_Reforco : true,
                                                                              .Hepatite_A : true,
                                                                              .Tetra_Viral : true,
                                                                              .DTP : true,
                                                                              .Varicela : false]],
                                                           vacinasAdolescente: [[ .HPV_1_Dose : false,
                                                                                  .HPV_2_Dose : true,
                                                                                  .Meningococica_C : true,
                                                                                  .Hepatite_B : false,
                                                                                  .Febre_Amarela_1_Dose : true,
                                                                                  .Dupla_Adulto_DT : true,
                                                                                  .Triplice_Viral : true,
                                                                                  .Pneumococica_23_Valente : false]],
                                                           vacinasAdulto: [[.Dupla_Adulto_DT : true,
                                                                            .Gripe : true,
                                                                            .Meningite_BACWY : true,
                                                                            .Hpv : false,
                                                                            .Pneumonia : true,
                                                                            .Herpes_Zoster : true,
                                                                            .Febre_Amarela : false,
                                                                            .Hepatite_B : true,
                                                                            .Triplice_Viral : true,
                                                                            .Hepatite_A : true,
                                                                            .Varicela : true]],
                                                           vacinasIdoso: [[ .Hepatite_B : true,
                                                                            .Febre_Amarela : true,
                                                                            .Dupla_Adulto_DT : false,
                                                                            .Pneumococica_23_Valente : false,
                                                                            .Gripe_Anual : true]],
                                                           vacinasGestante: [[.Hepatite_B : true,
                                                                              .Dupla_Adulto_DT : true,
                                                                              .dTpa : true,
                                                                              .Influenza : false]]),
                                                Dependente(nome: "Carol Silva", imagem: "carol.jpg", grupo: .Crianca, tipoSanguineo: .B_, hipertenso: true, diabetico: false, doadorOrgaos: true, pcd: false, vacinasCrianca: [[ .BCG : true,
                                                                                                                                                                                                                                 .Hepatite_B : true,
                                                                                                                                                                                                                                 .Penta_1_Dose : false,
                                                                                                                                                                                                                                 .Poliomielite_1_Dose : true,
                                                                                                                                                                                                                                 .Poliomielite_2_Dose : true,
                                                                                                                                                                                                                                 .Poliomielite_3_Dose : true,
                                                                                                                                                                                                                                 .Pneumococica_10 : true,
                                                                                                                                                                                                                                 .Rotavirus_Humano_1_Dose : false,
                                                                                                                                                                                                                                 .Meningococica_C : false,
                                                                                                                                                                                                                                 .Penta_2_Dose : false,
                                                                                                                                                                                                                                 .Pneumococica_10_Valente : false,
                                                                                                                                                                                                                                 .Rotavirus_Humano_2_Dose : true,
                                                                                                                                                                                                                                 .Febre_Amarela : true,
                                                                                                                                                                                                                                 .Triplice_Viral : true,
                                                                                                                                                                                                                                 .Pneumococica_Reforco : true,
                                                                                                                                                                                                                                 .Meningococica_Reforco : false,
                                                                                                                                                                                                                                 .Hepatite_A : false,
                                                                                                                                                                                                                                 .Tetra_Viral : true,
                                                                                                                                                                                                                                 .DTP : true,
                                                                                                                                                                                                                                 .Varicela : true]],
                                                           vacinasAdolescente: [[ .HPV_1_Dose : true,
                                                                                  .HPV_2_Dose : true,
                                                                                  .Meningococica_C : false,
                                                                                  .Hepatite_B : true,
                                                                                  .Febre_Amarela_1_Dose : true,
                                                                                  .Dupla_Adulto_DT : true,
                                                                                  .Triplice_Viral : true,
                                                                                  .Pneumococica_23_Valente : true]],
                                                           vacinasAdulto: [[.Dupla_Adulto_DT : true,
                                                                            .Gripe : true,
                                                                            .Meningite_BACWY : false,
                                                                            .Hpv : true,
                                                                            .Pneumonia : true,
                                                                            .Herpes_Zoster : false,
                                                                            .Febre_Amarela : true,
                                                                            .Hepatite_B : true,
                                                                            .Triplice_Viral : true,
                                                                            .Hepatite_A : true,
                                                                            .Varicela : false]],
                                                           vacinasIdoso: [[ .Hepatite_B : true,
                                                                            .Febre_Amarela : true,
                                                                            .Dupla_Adulto_DT : true,
                                                                            .Pneumococica_23_Valente : false,
                                                                            .Gripe_Anual : true]],
                                                           vacinasGestante: [[.Hepatite_B : true,
                                                                              .Dupla_Adulto_DT : true,
                                                                              .dTpa : false,
                                                                              .Influenza : true]])]
        
        
    )
    
    
    func getTempPerson() -> Person{
        
        return self.tempUser
        
    }
    
}
