//
//  REMOVERDEPOIS.swift
//  iVacina
//
//  Created by Alan Silva on 04/12/19.
//  Copyright © 2019 Alan Silva. All rights reserved.
//

import Foundation

class RemoverDepois {
    
    let tempUser: Titular = Titular(nome: "Alan Silva", email: "alan.bezerra10@gmail.com", imagem: "alan.jpg", grupo: .Adulto, tipoSanguineo: .A, hipertenso: false, diabetico: false, doadorOrgaos: false, pcd: false,
                                  vacinasCrianca: [ .BCG : false,
                                                     .Hepatite_B : false,
                                                     .Penta_1_Dose : false,
                                                     .Poliomielite_1_Dose : false,
                                                     .Poliomielite_2_Dose : false,
                                                     .Poliomielite_3_Dose : false,
                                                     .Pneumococica_10 : false,
                                                     .Rotavirus_Humano_1_Dose : false,
                                                     .Meningococica_C : false,
                                                     .Penta_2_Dose : false,
                                                     .Pneumococica_10_Valente : false,
                                                     .Rotavirus_Humano_2_Dose : false,
                                                     .Febre_Amarela : false,
                                                     .Triplice_Viral : false,
                                                     .Pneumococica_Reforco : false,
                                                     .Meningococica_Reforco : false,
                                                     .Hepatite_A : false,
                                                     .Tetra_Viral : false,
                                                     .DTP : false,
                                                     .Varicela : false],
                                  vacinasAdolescente: [ .HPV_1_Dose : false,
                                                         .HPV_2_Dose : false,
                                                         .Meningococica_C : false,
                                                         .Hepatite_B : false,
                                                         .Febre_Amarela_1_Dose : false,
                                                         .Dupla_Adulto_DT : false,
                                                         .Triplice_Viral : false,
                                                         .Pneumococica_23_Valente : false],
                                  vacinasAdulto: [.Dupla_Adulto_DT : false,
                                                   .Gripe : false,
                                                   .Meningite_BACWY : false,
                                                   .Hpv : false,
                                                   .Pneumonia : false,
                                                   .Herpes_Zoster : false,
                                                   .Febre_Amarela : false,
                                                   .Hepatite_B : false,
                                                   .Triplice_Viral : false,
                                                   .Hepatite_A : false,
                                                   .Varicela : false],
                                  vacinasIdoso: [ .Hepatite_B : false,
                                                   .Febre_Amarela : false,
                                                   .Dupla_Adulto_DT : false,
                                                   .Pneumococica_23_Valente : false,
                                                   .Gripe_Anual : false],
                                  vacinasGestante: [.Hepatite_B : false,
                                                     .Dupla_Adulto_DT : false,
                                                     .dTpa : false,
                                                     .Influenza : false],
                                  dependentes: [Pessoa(nome: "Davi Silva", imagem: "davi.jpg", grupo: .Crianca, tipoSanguineo: .B_, hipertenso: false, diabetico: false, doadorOrgaos: false, pcd: false,
                                                           vacinasCrianca: [ .BCG : false,
                                                                              .Hepatite_B : false,
                                                                              .Penta_1_Dose : false,
                                                                              .Poliomielite_1_Dose : false,
                                                                              .Poliomielite_2_Dose : false,
                                                                              .Poliomielite_3_Dose : false,
                                                                              .Pneumococica_10 : false,
                                                                              .Rotavirus_Humano_1_Dose : false,
                                                                              .Meningococica_C : false,
                                                                              .Penta_2_Dose : false,
                                                                              .Pneumococica_10_Valente : false,
                                                                              .Rotavirus_Humano_2_Dose : false,
                                                                              .Febre_Amarela : false,
                                                                              .Triplice_Viral : false,
                                                                              .Pneumococica_Reforco : false,
                                                                              .Meningococica_Reforco : false,
                                                                              .Hepatite_A : false,
                                                                              .Tetra_Viral : false,
                                                                              .DTP : false,
                                                                              .Varicela : false],
                                                           vacinasAdolescente: [ .HPV_1_Dose : false,
                                                                                  .HPV_2_Dose : false,
                                                                                  .Meningococica_C : false,
                                                                                  .Hepatite_B : false,
                                                                                  .Febre_Amarela_1_Dose : false,
                                                                                  .Dupla_Adulto_DT : false,
                                                                                  .Triplice_Viral : false,
                                                                                  .Pneumococica_23_Valente : false],
                                                           vacinasAdulto: [.Dupla_Adulto_DT : false,
                                                                            .Gripe : false,
                                                                            .Meningite_BACWY : false,
                                                                            .Hpv : false,
                                                                            .Pneumonia : false,
                                                                            .Herpes_Zoster : false,
                                                                            .Febre_Amarela : false,
                                                                            .Hepatite_B : false,
                                                                            .Triplice_Viral : false,
                                                                            .Hepatite_A : false,
                                                                            .Varicela : false],
                                                           vacinasIdoso: [ .Hepatite_B : false,
                                                                            .Febre_Amarela : false,
                                                                            .Dupla_Adulto_DT : false,
                                                                            .Pneumococica_23_Valente : false,
                                                                            .Gripe_Anual : false],
                                                           vacinasGestante: [.Hepatite_B : false,
                                                                              .Dupla_Adulto_DT : false,
                                                                              .dTpa : false,
                                                                              .Influenza : false]),
                                                Pessoa(nome: "Carol Silva", imagem: "carol.jpg", grupo: .Crianca, tipoSanguineo: .B_, hipertenso: false, diabetico: false, doadorOrgaos: false, pcd: false, vacinasCrianca: [ .BCG : false,
                                                                                                                                                                                                                                 .Hepatite_B : false,
                                                                                                                                                                                                                                 .Penta_1_Dose : false,
                                                                                                                                                                                                                                 .Poliomielite_1_Dose : false,
                                                                                                                                                                                                                                 .Poliomielite_2_Dose : false,
                                                                                                                                                                                                                                 .Poliomielite_3_Dose : false,
                                                                                                                                                                                                                                 .Pneumococica_10 : false,
                                                                                                                                                                                                                                 .Rotavirus_Humano_1_Dose : false,
                                                                                                                                                                                                                                 .Meningococica_C : false,
                                                                                                                                                                                                                                 .Penta_2_Dose : false,
                                                                                                                                                                                                                                 .Pneumococica_10_Valente : false,
                                                                                                                                                                                                                                 .Rotavirus_Humano_2_Dose : false,
                                                                                                                                                                                                                                 .Febre_Amarela : false,
                                                                                                                                                                                                                                 .Triplice_Viral : false,
                                                                                                                                                                                                                                 .Pneumococica_Reforco : false,
                                                                                                                                                                                                                                 .Meningococica_Reforco : false,
                                                                                                                                                                                                                                 .Hepatite_A : false,
                                                                                                                                                                                                                                 .Tetra_Viral : false,
                                                                                                                                                                                                                                 .DTP : false,
                                                                                                                                                                                                                                 .Varicela : false],
                                                           vacinasAdolescente: [ .HPV_1_Dose : false,
                                                                                  .HPV_2_Dose : false,
                                                                                  .Meningococica_C : false,
                                                                                  .Hepatite_B : false,
                                                                                  .Febre_Amarela_1_Dose : false,
                                                                                  .Dupla_Adulto_DT : false,
                                                                                  .Triplice_Viral : false,
                                                                                  .Pneumococica_23_Valente : false],
                                                           vacinasAdulto: [.Dupla_Adulto_DT : false,
                                                                            .Gripe : false,
                                                                            .Meningite_BACWY : false,
                                                                            .Hpv : false,
                                                                            .Pneumonia : false,
                                                                            .Herpes_Zoster : false,
                                                                            .Febre_Amarela : false,
                                                                            .Hepatite_B : false,
                                                                            .Triplice_Viral : false,
                                                                            .Hepatite_A : false,
                                                                            .Varicela : false],
                                                           vacinasIdoso: [ .Hepatite_B : false,
                                                                            .Febre_Amarela : false,
                                                                            .Dupla_Adulto_DT : false,
                                                                            .Pneumococica_23_Valente : false,
                                                                            .Gripe_Anual : false],
                                                           vacinasGestante: [.Hepatite_B : false,
                                                                              .Dupla_Adulto_DT : false,
                                                                              .dTpa : false,
                                                                              .Influenza : false])]
        
        
    )
    
    
    func getTempPerson() -> Titular{
        
        return self.tempUser
        
    }
    
}
